### ISSUE TITLE
Add a kick checker to the bot 

### ISSUE THREAD

**Issue by Galeath** [Meowhal/osu-ahr#10]
Even with all these measures that have been implemented, people can still force close the lobby by simply kicking everyone fast enough so that the referees/owner can not do anything about it or the people in the room are not able to !skip fast enough. I recommend for the bot to have the ability to check how many people the current host has kicked and if they pass a certain number, the host will get kicked by the bot and open up the room to the specific size again. I'm not sure how hard this is to do but I hope this is something that can be implemented.

**Comment by conquestace** [comment]
They can't force close the lobby if you turn off the lobby terminator plugin. The lobby will stay 0 people after everyone leaves and if you have lobby checker, it should reset to 16 people after host leaves every time.

**Comment by Galeath** [comment]
Ahh I see okay then thanks for the info

**Comment by Galeath** [comment]
Actually thinking about it, if that were the case then the lobby would still get closed, because no one is going to join a 16 room lobby all by themselves. Although I really do not want to put more work onto Meowhal, if the bot had some way to kick the host when they start kicking other players, it would still be useful to ensure that the room stay open for as long as possible.

**Comment by Meowhal** [comment]
Unfortunately, Banchobot does not report that the host has kicked someone. simply report that he left the game.
But we can detect it through webApi that used by match history page.
It's not easy, but it's technically possible.
there are some things to consider, such as when the same host kicks the same player multiple times, the hosts should not be skipped in such case.
Please let me know if there are other cases to consider.

I will work on prototyping this weekend

**Comment by Galeath** [comment]
I think that the host should also be kicked should they kick the referee or owner of the room. This should be made because I personally do not think that the owner/referee of the room has any reason to be kicked as there is the !skip command. If this could be implemented I think it would also be useful. 
Also, the owner/referee of the room is able to do a !mp kick/!mp ban command which should not kick them. Again as there is no reason for a ref/owner to be kicked for kicking people. Perhaps a timer between which a kick happens for the next kick to be able to be used.

**Comment by Meowhal** [comment]
thanks for your comment.
kicks against owner/ref should be penalized. Kicks by the !mp command should not be penalized.

**Comment by Meowhal** [comment]
finally i implemented the function.
Maybe it works.

**Comment by Meowhal** [comment]
still working
