### ISSUE TITLE
Issue with bot spam

### ISSUE THREAD

**Issue by Galeath** [Meowhal/osu-ahr#12]
So in the following link, I highlight that the bot has an issue when it can't decide whether there is a host change in the lobby, I looked through the older logs and found nothing like this back then. But I'm sure no owner of the bot would like to get punished for using the bot, however, I do not think there is a solution if the bot owner or an authorised user is in the lobby. Perhaps there could be a fix added in?
https://user-images.githubusercontent.com/79675527/111874165-da14da00-89ce-11eb-917d-1256efc03be7.mp4

**Comment by Meowhal** [comment]
I'm sorry for your silence penalty.
It seems to have been caused by an infinite loop of !mp host command.
This happens when !mp host command and the manual host transfer occur at the same time.

i fixed the problem and commited version 1.4.2
