### ISSUE TITLE
Dont work?

### ISSUE THREAD

**Issue by NickKruto** [Meowhal/osu-ahr#139]
I did everything according to the instructions.
![image](https://user-images.githubusercontent.com/98841244/178111960-6949e548-51d6-4242-aaa5-0db96c0f612f.png)

**Comment by xayanide** [comment]
The error pops up if you didn't change and set an account ID and IRC password in the `config/local.json` file.

Try doing it again, inside the `config` folder, there is a `default.json` file, copy it and paste it in that same folder, then rename it to `local.json`. Open that file and change the following lines accordingly.

```diff
    "irc": {
      "server": "irc.ppy.sh",
-      "nick": "your account id",
+      "nick": "MyAccountIDHere",
      "opt": {
        "port": 6667,
-        "password": "you can get password from 'https://osu.ppy.sh/p/irc'"
+        "password": "MyPasswordHere"
      }
    },
```

**Comment by NickKruto** [comment]
This is what I do
![image](https://user-images.githubusercontent.com/98841244/178140276-72101122-9721-42da-b72a-1407f3286d33.png)
![image](https://user-images.githubusercontent.com/98841244/178140357-e2f79951-6b7b-47c2-900e-135a5e659380.png)

**Comment by NickKruto** [comment]
This video helped
https://www.youtube.com/watch?v=8kYbBWgMfIQ
