### ISSUE TITLE
Link Discord

### ISSUE THREAD

**Issue by NickKruto** [Meowhal/osu-ahr#140]
![image](https://user-images.githubusercontent.com/98841244/178339506-25f32aa8-4564-4cd8-9c83-ebd75a6e859d.png)

**Comment by NickKruto** [comment]
![image](https://user-images.githubusercontent.com/98841244/178342369-44abd009-daa6-4996-882d-bd1b6c230b82.png)

**Comment by xayanide** [comment]
Hello, the error `[DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.` could mean that your bot is probably using an intent that hasn't been enabled for your Discord application yet.

Things you can do is to go to [Discord Developer Portal](https://discord.com/developers/applications), choose your application, proceed to the Bot settings section, and enable all the intents PRESENCE, SERVER MEMBERS & MESSAGE CONTENT (Not shown in the screenshot below) or the ones you're using.

![privleged-intents](https://user-images.githubusercontent.com/18362871/178526280-6999eeca-b14f-417c-8d90-1a362be4c0fc.png)
