### ISSUE TITLE
npm run start:discord not working.

### ISSUE THREAD

**Issue by ParaliyzedEvo** [Meowhal/osu-ahr#141]
I updated the ahr osu dev and it still didnt work. I am also using the dev branch and it still doesnt work. It keeps saying 
Loading log4js configuration from ./config/log_discord.json
[15:35:08.042][INFO] pre - Starting up...
[15:35:08.876][ERROR] discord_bot - @DiscordBot#start
Privileged intent provided is not enabled or whitelisted.
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\paral\Documents\osu-ahr-dev\osu-ahr-dev\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\paral\Documents\osu-ahr-dev\osu-ahr-dev\node_modules\discord.js\src\client\Client.js:254:7)
    at async DiscordBot.start (C:\Users\paral\Documents\osu-ahr-dev\osu-ahr-dev\dist\discord\DiscordBot.js:63:13)
![image](https://user-images.githubusercontent.com/107338855/179307137-629c5dc8-1375-45d0-97d1-c3a4f434d659.png)

**Comment by xayanide** [comment]
Potential duplicate of #140

https://github.com/Meowhal/osu-ahr/issues/140#issuecomment-1181904163
> Hello, the error `[DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.` could mean that your bot is probably using an intent that hasn't been enabled for your Discord application yet.
> 
> Things you can do is to go to [Discord Developer Portal](https://discord.com/developers/applications), choose your application, proceed to the Bot settings section, and enable all the intents PRESENCE, SERVER MEMBERS & MESSAGE CONTENT (Not shown in the screenshot below) or the ones you're using.
> 
> ![privleged-intents](https://user-images.githubusercontent.com/18362871/178526280-6999eeca-b14f-417c-8d90-1a362be4c0fc.png)

**Comment by NickKruto** [comment]
All on. I read instruction

**Comment by NickKruto** [comment]
![image](https://user-images.githubusercontent.com/98841244/179368201-b117c008-584d-48bd-b3c9-8b55b422b8db.png)

**Comment by ParaliyzedEvo** [comment]
> Potential duplicate of #140
> 
> [#140 (comment)](https://github.com/Meowhal/osu-ahr/issues/140#issuecomment-1181904163)
> 
> > Hello, the error `[DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.` could mean that your bot is probably using an intent that hasn't been enabled for your Discord application yet.
> > Things you can do is to go to [Discord Developer Portal](https://discord.com/developers/applications), choose your application, proceed to the Bot settings section, and enable all the intents PRESENCE, SERVER MEMBERS & MESSAGE CONTENT (Not shown in the screenshot below) or the ones you're using.
> > ![privleged-intents](https://user-images.githubusercontent.com/18362871/178526280-6999eeca-b14f-417c-8d90-1a362be4c0fc.png)

Thank you it works now
