### ISSUE TITLE
DISCORD BOT not responding to commands

### ISSUE THREAD

**Issue by powerdollkirby** [Meowhal/osu-ahr#148]
the bot logs in, whenever i try to use a command /make /info or whatever, it doesnt work

**Comment by Xayanide** [comment]
Use `!<command name>` when using commands in the osu! multiplayer lobby chat.

Use `<command name>`, no prefix when using ahr commands inside the command line interface.

**Comment by xayanide** [comment]
Can you provide some error logs that were shown in the command line interface during that incident?

**Comment by Caassiiee** [comment]
there's no longs, literally the bot doesn't respond, it works locally but in a discord bot isn't working at all 
![vuhEDxqtRC](https://user-images.githubusercontent.com/105698999/193482320-15352496-3a1d-46cb-ba34-44099e7d7b4d.png)

**Comment by Caassiiee** [comment]
Nvm i didn't read correctly, its says *Only users with this role will be able to manage the lobby. You should assign this role to your own account.*
so you have to have the same role as the bot.
![CSoi0YN2re](https://user-images.githubusercontent.com/105698999/193482920-325948e2-90e4-42dc-aa7f-058956ac2280.png)

**Comment by Caassiiee** [comment]
Nvm i didn't read correctly, its says Only users with this role will be able to manage the lobby. You should assign this role to your own account.
so you have to have the same role as the bot.

**Comment by powerdollkirby** [comment]
Nvm i didn't read correctly, its says Only users with this role will be able to manage the lobby. You should assign this role to your own account.
so you have to have the same role as the bot.
![CSoi0YN2re](https://user-images.githubusercontent.com/105698999/193483013-b965f76e-49ac-43de-ba41-65e520ad6d63.png)
