### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by GoodPro712** [Meowhal/osu-ahr#25]
### Description
Integration with a Discord channel through a bot, and allow commands to be run through the bot the execute for the lobby.

### Features
Chat bridge between Discord and in-game osu! chat.
Executing commands through Discord such as starting the game, acting like a console. (with only specified user ids to be able to run these commands)

**Comment by Meowhal** [comment]
Thanks for translation GoodPro712.
Is it a security or privacy issue to transfer game chats to a Discord server without the player's consent?
Embarrassingly, I'm not familiar with discord integration.

**Comment by GoodPro712** [comment]
I'm not completely sure. I'm pretty sure at least most players wouldn't mind, though maybe a message could be sent in chat or something similar to notify the players?

**Comment by GoodPro712** [comment]
I think you could use something like [discord.ts](https://github.com/OwenCalvin/discord.ts) for writing a Discord bot in typescript.

**Comment by Meowhal** [comment]
thx for link
It looks interesting, so I'll work on coding

**Comment by Meowhal** [comment]
The Discord integration feature is still in testing, but it's working. Please use it if you are interested.

https://github.com/Meowhal/osu-ahr/tree/dev-discord

**Comment by GoodPro712** [comment]
Unfortunately I am unable to test it currently, although I am happy to translate Japanese.
