### ISSUE TITLE
Regulation always violated

### ISSUE THREAD

**Issue by AAKoder** [Meowhal/osu-ahr#27]
I'm trying to make an ahr room but every map picked always cause regulation violation, causing unable to pick any map

![image](https://user-images.githubusercontent.com/52598050/129860820-18c60182-a6d0-43d7-8102-046cb3fd5f7b.png)
![image](https://user-images.githubusercontent.com/52598050/129861145-2cd0b7bc-f6d4-4bfd-8cb3-319b4a6560df.png)

**Comment by Meowhal** [comment]
which version do you use?
you can check version from `./package.json` file.

**Comment by AAKoder** [comment]
1.4.3, I think it happen with the latest version as well

**Comment by Meowhal** [comment]
thx for reporting. i fixed the bug,
I'm ashamed that the bug has been left unattended for a long time.

**Comment by AAKoder** [comment]
Thanks :)
