### ISSUE TITLE
Why does bancho keep sending me stat messages?

### ISSUE THREAD

**Issue by AAKoder** [Meowhal/osu-ahr#28]
Why does bancho keep sending me stat messages?
![image](https://user-images.githubusercontent.com/52598050/129989011-9d25ab21-2ab4-474a-94ba-70cc3f610573.png)

**Comment by Meowhal** [comment]
The bot periodically runs the STAT command to detect if the host is AFK.

**Comment by AAKoder** [comment]
okok, thanks
