### ISSUE TITLE
Bot don't give a host 

### ISSUE THREAD

**Issue by nikita9079** [Meowhal/osu-ahr#3]
I must say right away that it’s possible that something I am doing wrong or did not understand is wrong and the bot is working.
It's my problem i can make a room commands is working but if i join bot dont give me a host i'm trying with another player ,i see massage on YouTube bot is working if people more that one this dosen't help also trying commands like !abort and !skip.
https://imgur.com/U33oKge

**Comment by Meowhal** [comment]
Thanks for providing info.
It seems that the funcrion to send message to the multiplayer lobby is not working.
The API of chat in the multiplayer lobby may have changed and it is not working.

I'll look it up after work today.

**Comment by Meowhal** [comment]
I tried with my account and it worked.
can you send log files in osu-ahr/logs direcotry?

**Comment by nikita9079** [comment]
Sure
https://yadi.sk/d/UifRVMopE8FkiA

**Comment by nikita9079** [comment]
I reinstall a few times and game bot start work , i dont know why this happened ty for help ,and ty for bot if you need help with translations into English or Russian say so.
