### ISSUE TITLE
Auto Host Rotation 

### ISSUE THREAD

**Issue by Xayanide** [Meowhal/osu-ahr#37]
I got skipped in an auto host rotation lobby once, kind of rare.

The bot has a flaw when a host leaves right before the game starts.

I was not the one using the bot though.

How it happened:

Let's call the guy as Player B, the host that left right before the game starts with their pick.
Let's call the guy who gets host after player B. Player A. Player A gets the host after Player B left.

---

1. Player B left as his pick is about to start.

2. Player A receives host as the game starts with Player B's pick. 
 
3. After the game, the bot switches the host to the next player before Player A gets to pick a map.

---

Player A should've been able to pick a map after playing Player B's pick when Player B left while his pick started.

The bot probably thought Player B's pick was Player A's pick when Player B left as the game started, so, after the game with Player B's pick, it switched the host to the next player after Player A.

**Comment by Meowhal** [comment]
Fixed the issue.
The issue should not occur with version 1.5.8 and above.

Thank you for the report.
