### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by SpicyDice** [Meowhal/osu-ahr#43]
how do i put my osu irc password directly into the code instead of putting it on local.json?

https://github.com/Meowhal/osu-ahr/blob/master/config/default.json
```json
{
  "irc": {
    "server": "irc.ppy.sh",
    "nick": "your account id",
    "opt": {
      "port": 6667,
      "password": "you can get password from 'https://osu.ppy.sh/p/irc'"
    }
  },
```

(https://github.com/Meowhal/osu-ahr/blob/master/src/libs/irc.js)
```typescript
function Client(server, clientNick, opt) {
    var self = this;
    self.opt = {
        server: server,
        nick: clientNick,
        userName: 'nodebot',
        realName: 'nodeJS IRC client',
        password: null,
 ```
 can i put my osu irc password in there and will it work?

**Comment by Meowhal** [comment]
rewrite the line according to whether you want to use cli or discord.

https://github.com/Meowhal/osu-ahr/blob/a2c1427a5faed1018070c8f61682bf2188c3f52e/src/cli/index.ts#L28
https://github.com/Meowhal/osu-ahr/blob/a2c1427a5faed1018070c8f61682bf2188c3f52e/src/discord/index.ts#L27

```typescript
let ircClient = new irc.Client(c.server, c.nick, { port: 6667, password: "your password" });
```

or 

```typescript 
c.opt.password = "your password";
let ircClient = new irc.Client(c.server, c.nick, c.opt);
```

**Comment by SpicyDice** [comment]
Thank you!
For discord token though, I put them directly between (tokenhere)
https://github.com/Meowhal/osu-ahr/blob/e5d328c1e70d7fee6125f919f4c31eb0a6176737/src/discord/DiscordBot.ts#L84
and here
https://github.com/Meowhal/osu-ahr/blob/199a661afc4938160b2fd9537e48d4fc87081e6d/src/trials/AppendersTrial.ts#L55
is that alright?

**Comment by Meowhal** [comment]
yep, but you can ignore trial files.
trial is used to check the behavior of the program and is not used in normal operation.

**Comment by ZeroPyrozen** [comment]
> for discord token though I put my discord token directly here by replacing this.cfg.token in between the ()

Just make sure to not share your discord token by pushing to your fork by adding it to .gitignore.

**Comment by SpicyDice** [comment]
> 
```typescript
c.opt.password = "your password";
let ircClient = new irc.Client(c.server, c.nick, c.opt);
```
using that ^, one gives an error. the first one works, i just tried this 2nd one and found out it doesn't work.

```
> osu-ahr@1.5.13 start:discord
> ts-node src/discord/index.ts

starting up...
[22:23:57.955][ERROR] cli - TypeError: Cannot assign to read only property 'password' of object '#<Object>'
    at Object.<anonymous> (/home/runner/ahr/src/discord/index.ts:29:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/runner/ahr/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/ahr/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at main (/home/runner/ahr/node_modules/ts-node/src/bin.ts:331:12)
    at Object.<anonymous> (/home/runner/ahr/node_modules/ts-node/src/bin.ts:482:3)
    ```

**Comment by ZeroPyrozen** [comment]
`IIrcConfig` is interface not class so it need to be implemented before usage. Create `IrcConfig` and `ClientOpts` class first in `TypedConfig.ts`

```ts
export class ClientOpts implements IClientOpts {

}

export class IrcConfig implements IIrcConfig {
  server: string;
  nick: string;
  opt: IClientOpts;
  constructor(server: string, nick: string, opt: ClientOpts){
    this.server = server;
    this.nick = nick;
    this.opt = opt;
  }
}
```

then create the object in the `index.ts`

```ts
  var cOpt : ClientOpts =  {port: 6667,password: "yourPassword"};
  var c = new IrcConfig("irc.ppy.sh","YourNickname",cOpt);
```

**Comment by SpicyDice** [comment]
> IIrcConfig is interface not class so it need to be implemented before usage. Create IrcConfig and ClientOpts class first in TypedConfig.ts then create the object in the index.ts

i did what you suggested on typedconfig.ts but
i was not sure where or how to put those var in src/discord/index.ts, so here are the things i changed in index.ts

I changed this from:
https://github.com/Meowhal/osu-ahr/blob/a2c1427a5faed1018070c8f61682bf2188c3f52e/src/cli/index.ts#L28
to:
```ts
    var cOpt : ClientOpts =  {port: 6667,password: "passwordhere"};
    var c = new IrcConfig("irc.ppy.sh","usernamehere",cOpt);
    c.opt.password = "passwordhere";
    let ircClient = new irc.Client(c.server, c.nick, c.opt);

```
i ran the bot.
i got an error on console that ClientOpts and IrcConfig can't be found.
```
TSError: ⨯ Unable to compile TypeScript:
src/discord/index.ts:11:12 - error TS2304: Cannot find name 'ClientOpts'.
src/discord/index.ts:12:13 - error TS2304: Cannot find name 'IrcConfig'.
```
so

I changed this from:
https://github.com/Meowhal/osu-ahr/blob/a2c1427a5faed1018070c8f61682bf2188c3f52e/src/cli/index.ts#L5
to:
```ts
import { getIrcConfig, ClientOpts, IrcConfig } from "../TypedConfig";
```
I ran the bot again.
I got an error  `Cannot initialize outer scoped variable 'c' in the same scope as block scoped declaration 'c'.`
so

I changed this from:
https://github.com/Meowhal/osu-ahr/blob/a2c1427a5faed1018070c8f61682bf2188c3f52e/src/cli/index.ts#L20
to:
```ts
    var c = getIrcConfig();
```

I ran the bot
it worked.
did I do it right or did I do something wrong and it wasn't supposed to be done like that?

**Comment by ZeroPyrozen** [comment]
yes that's the one, `var c` that I mentioned above should be used with `const c = getIrcConfig();` commented out

**Comment by SpicyDice** [comment]
oooh! so it's supposed to look like this in src/discord/index.ts since i use the [discord](https://github.com/Meowhal/osu-ahr/blob/master/src/discord/index.ts) one, thank you so much for your time!
https://github.com/Meowhal/osu-ahr/blob/dfe4a4e4d5ce985bd5115eedc238edc7eb6931b2/src/discord/index.ts#L6
``` ts
//import { getIrcConfig } from "../TypedConfig"; 
import { getIrcConfig, ClientOpts, IrcConfig } from "../TypedConfig";
```
Lines 16 to 27
https://github.com/Meowhal/osu-ahr/blob/dfe4a4e4d5ce985bd5115eedc238edc7eb6931b2/src/discord/index.ts#L16
```ts
try {
    log4js.configure(config_path);
    
    //const c = getIrcConfig(); 
    var cOpt : ClientOpts =  {port: 6667,password: "mypassword"};
    var c = new IrcConfig("irc.ppy.sh","myusername",cOpt);
    if (c.nick == "your account id" || c.opt.password == "you can get password from 'https://osu.ppy.sh/p/irc'") {
        logger.error("you must enter your account name and irc password in the config file. ");
        logger.error("you can get the password from 'https://osu.ppy.sh/p/irc' ");
        logger.error("Copy config/default.json to config/local.json, and enter your id and irc password.");
        process.exit(1);
    }

    c.opt.password = "mypassword";
    let ircClient = new irc.Client(c.server, c.nick, c.opt);
```

**Comment by ZeroPyrozen** [comment]
Just make sure that `index.ts` doesn't get commited to your public repository. You can create another index file like `index-local.ts` then on `package.json` change this line `"start:discord": "ts-node src/discord/index.ts",` to `"start:discord": "ts-node src/discord/index-local.ts",` then add the path to gitignore.
