### ISSUE TITLE
Version can be shown as undefined in-game

### ISSUE THREAD

**Issue by Xayanide** [Meowhal/osu-ahr#68]
**Describe the bug**
Affects cli and discord cli, everytime a user runs osu-ahr directly with node (e.g `node dist/cli/index.js`) instead of the npm script (e.g `npm start` or `npm start:discord`), the version that will be shown in-game is `undefined`.

I see in code that there was a nullish coalescing operator that would show it as 0.0.0, but it on other conditions it was shown as `undefined` which was unintended.

I think the reason why it is shown as undefined is because the version shown depends on the process' npm script being run at.

A quick solution would be to depend the version shown using the `package.json` file, but I think that is unsafe and not good overall to risk it unless it is acceptable in this case.

**Affected version**
1.5.17

**Steps to reproduce**
If haven't compiled yet run.
```js
npm run clean
```
```js
npm run build
```
1. Run osu-ahr from compiled dist directly instead of the npm script.

Cli
```js
node dist/cli/index.js
```
Discord Cli
```js
node dist/discord/index.js
```

2. Make or enter a lobby

3. Use `!version` or `!info` command in-game.

**Expected behavior**
Show the correct version or `0.0.0` if unknown.

**Actual behavior**
Shown as undefined to the end user.

**Comment by Meowhal** [comment]
The !info shows 0.0.0, but I forgot to use the nullish coalescing operator in the !version.
I added code to make it relatively safe to display the version via node, so please check it out.

**Comment by Meowhal** [comment]
fixed
