### ISSUE TITLE
Regulation settings aren't enforced

### ISSUE THREAD

**Issue by oblivion2k** [Meowhal/osu-ahr#7]
Apologies if this issue exists already in the TODO section, it's not translated to English.

Regulation settings are able to be set, but not currently enforced. 

How to recreate:
1.Create a lobby with any name
2.Set regulations, for example `regulation star_min 3 star_max=5 len_max=300`
3.Enter the lobby and pick a map outside of the 3.00 to 5.00 range, or have another player in the lobby pick a map outside of that range.
4. Notice that the map is able to be selected and played without any enforcement of the regulation setting.

**Comment by Meowhal** [comment]
Thanks for letting me know.
There was a command to enable it, but I forgot to write in the documentation.
Also, the command was a bit confusing, so I added a new command.

```sh
regulation enable 
regulation disabled
```
The default behavior is disabled.
You can change this behavior by rewriting the config file(config/default.json or config/local.json).
```json
"mapChecker": {
    "enabled": true,
    "star_min": 3.00,
    "star_max": 5.00,
    "length_min": 0,
    "length_max": 300
  }
```
I will rewrite the readme if I have time.

**Comment by conquestace** [comment]
I am getting error "mapChecker - couldn't find map id: 1677077, titleSCARTON - ... "

**Comment by Meowhal** [comment]
There was a bug and it wasn't working well.
Version 1.3.5 may works fine.
