### ISSUE TITLE
Map Checker Issue?

### ISSUE THREAD

**Issue by praha38** [Meowhal/osu-ahr#8]
Hi.
First, I really appreciate for your contribution. and I can't use English very well, sorry for poor English.

I think mapChecker doesn't work properly.
and I also enabled regulation (command: regulation enable)

`[WARN] mapChecker - couldn't find map id:<map id>, title:<map title>`
This is what console said, so server don't(can't) regulate beatmap's difficulty, length.

I think I missed something. But I can't really find solution.
Is there any method to solve this issue?

**Comment by conquestace** [comment]
I am guessing we don't have access to the osu! api. Just need to figure how to get oauth working. I looked through the code but I am noob.

**Comment by Meowhal** [comment]
Thank you for reporting.

I have implemented two methods to check the difficulty of the map.
One is to load a web page and the other is to load a web API.
Normally the web page version is used, but it didn't work due to a bug.
I fixed that bug. Try version 1.3.5.

I'm preparing to write a guide on how to use the WEB API.

**Comment by praha38** [comment]
Wow, I really didn't expect this issue fixed fast.
and I swear, I'm spreading word of your work. So keep it up!

**Comment by praha38** [comment]
Well, I think I found another bug.
AutoStartTimer seems always enabled when map regulation function has enabled.

I think it's not supposed to be work like it.

**Comment by Meowhal** [comment]
I fixed codes.
I hope the problem is solved.

**Comment by praha38** [comment]
Thank you.
You also improved regulation function. I really like it.
