### ISSUE TITLE
Organize ESLint rules

### ISSUE THREAD

**Issue by Xayanide** [Meowhal/osu-ahr#87]
Group: `Refactorization`
- [ ] Organize ESLint rules

Size: `Small`
> For they were inconsistently sorted at the moment. Not sure how is it going to be sorted or categorized yet.

If against, please send a concise statement why.

**Comment by Meowhal** [comment]
I didn't sort it.

now, I sorted the rules alphabetically by [YAML Sort](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort)
