### ISSUE TITLE
Full and complete usage of template literals

### ISSUE THREAD

**Issue by Xayanide** [Meowhal/osu-ahr#88]
Group: `Refactorization`
- [x] https://github.com/Meowhal/osu-ahr/pull/86
- [x] https://github.com/Meowhal/osu-ahr/pull/91 Full and complete usage of template literals.

Size: `Medium`
> For us to take more advantage of ES6's template literals, [string interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) instead of using string concatenation, I thought that they're less difficult to read compared to string concat, I saw both of these were used inconsistently or maybe that was preferred?
> Will involve 2 ESLint rules for refactoring purposes.
[template-curly-spacing](https://eslint.org/docs/rules/template-curly-spacing)
[prefer-template](https://eslint.org/docs/rules/prefer-template)
> ```yaml
>  template-curly-spacing:
>    - "error"
>  prefer-template:
>    - "error"
> ```
> **Before**:
> ```ts
> try {
>  fruit = apple;
>  eat(fruit)
> } catch (err: any) {
>   console.log('Argh! This fruit called %s is rotten! Error:\n%s\n%s', fruit, err.message, err.stack);
> }
> ```
> **After**:
> ```ts
> try {
>  fruit = apple;
>  eat(fruit)
> } catch (err: any) {
>   console.log(`Argh! This fruit called ${fruit} is rotten! Error:\n${err.message}\n${err.stack}`);
> }
> ```
> and 1 extra rule just in-case.
[no-useless-concat](https://eslint.org/docs/rules/no-useless-concat)
> ```yaml
>  no-useless-concat:
>    - "error"
> ```
> https://github.com/Meowhal/osu-ahr/blob/fc653923eda87363d78e90fb4b390be6c9ac1e8c/src/tests/LobbyTest.ts#L455
> ```ts
> // equivalent
>         return 'abc';
> ```

I will be making a PR for this sometime soon.
If against, please state a concise statement why.

**Comment by Meowhal** [comment]
At the beginning of development, format strings were sometimes used because they could delay the timing of string concatenation, considering the possibility of no output due to the log level.
But this kind of performance tuning is pointless except in critical areas. Now it is too much trouble to remember how to write format strings for me. I can unify it with literal strings.
