### ISSUE TITLE
Add !mp size 16 and !mp password after every rotation

### ISSUE THREAD

**Issue by conquestace** [Meowhal/osu-ahr#9]
Some mischievous hosts will change lobby room size or add a password ruining the lobby. If the IRC bot types !mp size 16 and !mp password lobby is reset everytime.

**Comment by Meowhal** [comment]
How can players or host add a password?
I thought that only the lobby owner can do it.

I'm considering add a function that keeps the room size.

**Comment by conquestace** [comment]
just change password on the left side near lobby name

**Comment by Meowhal** [comment]
Does it work in a tournament lobby?

**Comment by conquestace** [comment]
kicking people and changing lobby size can be done be the host not sure about password, but if they can !mp password is a solution

**Comment by Meowhal** [comment]
I added LobbyKeeper plugin.
It can keep teammode, scoremode, lobby size, lobby password and mods.
you can configure the plugin via "config/local.json" file
```json

"LobbyKeeper": {
  "mode": { "team": 0, "score": 3  },
  "size": 8,
  "password": "",
  "mods": "freemod"
}

```
bot will post `!mp set 0 3 8`, `!mp password` and `!mp mods freemod` at the end of each match.
and post `!mp set 0 3 8` when host kicked someone.

null means no control.
if you want to keep only lobby size.
```json

"LobbyKeeper": {
  "mode": null,
  "size": 16,
  "password": null,
  "mods": null
}
```
bot will post `!mp size 16`.

also you can configure the bot via ingame chat 
| command | desc |
|:-|:-|
|`*keep password ` | post `!mp password` |
|`*keep password pass1234`| post `!mp password pass1234`|
|`*no keep password`| disable |
|`*keep size 16` | post `!mp size 16`|
|`*no keep size` | disable |
|`*keep mode 0 0` | post `!mp set 0 0`|
|`*no keep mode` | disable |
|`*keep mods freemod` | post `!mp mods freemod` |
|`*no keep mods` | disable |

don't worry, only authorized users can use the * command.

**Comment by conquestace** [comment]
Looks like it works nicely! 

Unfortunately, there is nothing that will actually force a lobby to stay permanently a certain mod (like DT) as host can always take out DT despite *keep mods DT. Only fix I can see is having !mp mods be applied **after** a map has been picked rather than once host is selected. Or apply !mp mods right before the match starts, but this one has problems since if you do !mp mods DT freemod, then if someone had selected HD for themselves, they would go into the match with only DT and no HD.

^^^
these problems don't need to be addressed at all btw, they're just me nitpicking something that is already very good!
